### ISSUE TITLE
How does this project compare to your other project MarvelHeroes in terms of Architecture esp MVVM side

### ISSUE THREAD

**Issue by rinav** [skydoves/DisneyMotions#8]
I am little confused when comparing both your projects 
As both use MVVM with Repository pattern and Coroutines what is the major difference between the two setup comparing only the architecture excluding the UI.

Thanks for sharing this great repo, It serves as a great reference point to building modern android app with good architecture implementation

**Comment by skydoves** [comment]
@rinav 
Hi, thank you for your interest.

There is no major difference between DisneyMotions and  MarvelHeroes in the architectural points.
I think you got confused because of the `client` from the MarvelHeros,  the main role of the `client` is an implementation of a `service` and separating the network call from the repository. 
This repository is a really really little sample implementation of the real architectural project in the real world and the concept of the `client` helps to unit testing easier in the network call.

**Comment by rinav** [comment]
@skydoves Yes you understood it right, that was probably what I was thinking. Thanks for the quick respons.
